[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "7.1"
addopts = "-ra"
testpaths = [
    "nion/utils/test",
]
python_files = "*_test.py"
